images:
- # !! - container image 경로
  name: grpc-ping-pong
  newName:
  newTag:

patches:
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: grpc-ping-pong
      annotations:
        # !! - AWS Certificate Manager에 등록한 self-signed certificate의 ARN
        alb.ingress.kubernetes.io/certificate-arn:

resources:
- ./base/deployment.yml
- ./base/service.yml
- ./base/ingress.yml
